### ISSUE TITLE
Handle git panic on new repo

### ISSUE THREAD

**Issue by bradleyfalzon** [bradleyfalzon/revgrep#6]
```
panic: no version control repository found

goroutine 1 [running]:
panic(0x4d0500, 0xc42000a4e0)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/bradleyfalzon/revgrep.Changes(0x0, 0x0, 0x561380, 0xc42002a008, 0x5613c0, 0xc42002a018)
        /home/bradleyf/go/src/github.com/bradleyfalzon/revgrep/revgrep.go:36 +0x54e
main.main()
        /home/bradleyf/go/src/github.com/bradleyfalzon/revgrep/cmd/revgrep/main.go:14 +0xe5
```

Related to #5

**Comment by bradleyfalzon** [comment]
Fixed in 8d814c0640f3a2fe43f767556d6beddb842d9844
